[build]
  command = "npm run build"
  publish = ".next" # Change this to match your Next.js build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
[[plugins]]
  package = "@netlify/plugin-nextjs"